import Head from "next/head";
import Image from "next/image";
import PostList from "../components/PostList";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h3 className="text-center mb-5">Posts</h3>
         <PostList posts={posts}/>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=10`
  );
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
};
